apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data: #This is my main config map block which is mentioned inside data block
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  # these are replica set labels
  labels:
    project: {{ .Values.deployment.projname }}
    component: payment
    tier: {{ .Values.deployment.tier }}
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: {{ .Values.deployment.projname }}
      component: payment
      tier: {{ .Values.deployment.tier }} 
  # pod definition
  template:
    metadata:
      labels:
        project: {{ .Values.deployment.projname }}
        component: payment
        tier: {{ .Values.deployment.tier }}
    spec:
      containers:
      - name: payment
        image: "{{ .Values.deployment.imagename }}:{{ .Values.deployment.imageversion }}"
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: payment
# This is readiness probe(getting application ready after start/restart)
        readinessProbe:
          httpGet:
            path: {{ .Values.deployment.path }}
            port: liveness-port
          failureThreshold: 1
          periodSeconds: {{ .Values.deployment.periodseconds }}

# This is liveness probe(checking health of application)
        livenessProbe:
          httpGet:
            path: {{ .Values.deployment.path }}
            port: liveness-port
          failureThreshold: 1
          periodSeconds: {{ .Values.deployment.periodseconds }}