apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    project: {{ .Values.service.projname }}
    component: payment
    environment: dev
  ports:
    - protocol: TCP
      port: {{ .Values.service.serviceport }}        #service port
      targetPort: 8080  #container port