apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data: #This is my main config map block which is mentioned inside data block
  MONGO: "true"
  REDIS_URL: {{ .Values.configmap.redis_URL }}
  MONGO_URL: {{ .Values.configmap.mongo_URL }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: user
    tier: backend
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: user
      tier: backend  
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: user
        tier: backend
    spec:
      containers:
      - name: user
        image: "{{ .Values.deployment.imageRepo }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: user
# This is readiness probe(getting application ready after start/restart)
        readinessProbe:
          httpGet:
            path: {{ .Values.deployment.health }}
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15

# This is liveness probe(checking health of application)
        livenessProbe:
          httpGet:
            path: {{ .Values.deployment.health }}
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15