apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: user
    environment: dev
  ports:
    - protocol: TCP
      port: {{ .Values.service.serviceport }}          #service port
      targetPort: 8080  #container port