apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  my.cnf: |
    {{ .Values.configmap.cnf }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: mysql
    tier: db
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: mysql
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.deployment.imageRepo }}:{{ .Values.deployment.imageVersion}}"
        imagePullPolicy: Always
        # readinessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 3306
        #   initialDelaySeconds: 20
        #   periodSeconds: 5
        volumeMounts:
        - name: mysql-config
          mountPath: {{ .Values.deployment.mountpath }}
          subPath: my.cnf

      volumes:
        - name: mysql-config
          configMap:
            name: mysql