apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: {{ .Values.service.serviceport }} # service port
      targetPort: 3306 # container port