apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: redis
    tier: db
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: redis
      tier: db   
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: "{{ .Values.deployment.imageRepo }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
# This is readiness probe(getting application ready after start/restart)
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10

# This is liveness probe(checking health of application)
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5