apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: redis
    environment: dev
  ports:
    - protocol: TCP
      port: {{ .Values.service.serviceport }} #service port
      targetPort: 6379   #container port