apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data: #This is my main config map block which is mentioned inside data block
  CART_ENDPOINT: "{{ .Values.configmap.cartname }}:{{ .Values.configmap.cart_portno }}"
  DB_HOST: {{ .Values.configmap.db_hostname }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  # these are replica set labels
  labels:
    project: {{ .Values.deployment.projname }}
    component: {{ .Values.deployment.componentname }}
    tier: {{ .Values.deployment.tier }}
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: {{ .Values.deployment.projname }}
      component: {{ .Values.deployment.componentname }}
      tier: {{ .Values.deployment.tier }} 
  # pod definition
  template:
    metadata:
      labels:
        project: {{ .Values.deployment.projname }}
        component: {{ .Values.deployment.componentname }}
        tier: {{ .Values.deployment.tier }}
    spec:
      containers:
      - name: shipping
        image: "{{ .Values.deployment.imagename }}:{{ .Values.deployment.imageversion }}"
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: shipping
# This is readiness probe(getting application ready after start/restart)
        readinessProbe:
          httpGet:
            path: {{ .Values.deployment.path }}
            port: liveness-port
          failureThreshold: 1
          periodSeconds: {{ .Values.deployment.periodseconds }}

# This is liveness probe(checking health of application)
        livenessProbe:
          httpGet:
            path: {{ .Values.deployment.path }}
            port: liveness-port
          failureThreshold: 1
          periodSeconds: {{ .Values.deployment.periodseconds }}