apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data: #This is my main config map block which is mentioned inside data block
  REDIS_HOST: {{ .Values.configmap.redis_host }}
  CATALOGUE_HOST: {{ .Values.configmap.catalogue_host }}
  CATALOGUE_PORT: {{ .Values.configmap.catalogue_port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: cart
    tier: backend
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: cart
      tier: backend  
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: cart
        tier: backend
    spec:
      containers:
      - name: cart
        image: "{{ .Values.deployment.imagename }}:{{ .Values.deployment.imageversion }}"
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: cart
# This is readiness probe(getting application ready after start/restart)
        readinessProbe:
          httpGet:
            path: {{ .Values.deployment.path }}
            port: liveness-port
          failureThreshold: 1
          periodSeconds: {{ .Values.deployment.periodseconds }}

# This is liveness probe(checking health of application)
        livenessProbe:
          httpGet:
            path: {{ .Values.deployment.path }}
            port: liveness-port
          failureThreshold: 1
          periodSeconds: {{ .Values.deployment.periodseconds }}