apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: cart
    environment: dev
  ports:
    - protocol: TCP
      port: 8080          #service port
      targetPort: 8080  #container port
