apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: rabbitmq
    tier: db
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: rabbitmq
      tier: db   
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: "{{ .Values.deployment.imageRepo }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
# This is readiness probe(getting application ready after start/restart)
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 15
          periodSeconds: 10

# This is liveness probe(checking health of application)
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 20
          periodSeconds: 5