apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: rabbitmq
    environment: dev
  ports:
    - protocol: TCP
      port: {{ .Values.service.serviceport }}         #service port
      targetPort: 5672   #container port