apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: roboshop
data:
  nginx.conf: {{ .Values.configmap.nginx_conf }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  # these are replica set labels
  labels:
    project: {{ .Values.deployment.projname }}
    component: frontend
    tier: {{ .Values.deployment.tier }}
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: {{ .Values.deployment.projname }}
      component: frontend
      tier: {{ .Values.deployment.tier }}
  # pod definition
  template:
    metadata:
      labels:
        project: {{ .Values.deployment.projname }}
        component: frontend
        tier: {{ .Values.deployment.tier }}
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.deployment.imagename }}:{{ .Values.deployment.imageversion }}"
        imagePullPolicy: Always
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: {{ .Values.deployment.path }}
            port: liveness-port
          failureThreshold: 1
          periodSeconds: {{ .Values.deployment.periodseconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.deployment.path }}
            port: liveness-port
          failureThreshold: 1
          periodSeconds: {{ .Values.deployment.periodseconds }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: frontend