apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: catalogue
    environment: dev
  ports:
    - protocol: TCP
      port: {{ .Values.service.serviceport }}   #service port
      targetPort: 8080 #container port